spring:
  application:
    name: matchalot

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    properties:
      ssl: false
    pool:
      enable: true
      initial-size: 2
      max-size: 10

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 283628099860-46e7o3f0a3r9t8neg3mp3n09kl0j5ea5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            #client-name: Google

app:
  frontend:
    url: http://localhost:3000

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
