spring:
  application:
    name: matchalot

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    properties:
      ssl: false
    pool:
      enable: true
      initial-size: 2
      max-size: 10

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "283628099860-0ulj37lbns6csn3aeq5e03dcb40d9b8v.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - openid
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google

app:
  frontend:
    url: http://localhost:3000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
